export const DEFAULT_COLS = 80;
export const DEFAULT_ROWS = 24;
export const TERMINAL_FONT_SIZE = 13;
export const TERMINAL_FONT_FAMILY = "'JetBrains Mono', 'Fira Code', monospace";
export const PTY_KILL_TIMEOUT_MS = 3000;
export const RING_BUFFER_MAX_BYTES = 100 * 1024; // ~100KB per session
export const DEFAULT_SIDEBAR_WIDTH = 280;
export const MIN_SIDEBAR_WIDTH = 200;
export const MAX_SIDEBAR_WIDTH = 500;
export const LAYOUT_PERSIST_DEBOUNCE_MS = 500;
